# -*- coding: utf-8 -*-
"""PASS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_IhOsP6DU9H3IoRPM1LhxrYLdxM4wBBs
"""

import re
def check_password_strength (password):
    if len (password) < 8:
     return  "weak:password must have at least 8 characters"

    if not any (char.isdigit() for char in password):
        return "weak : password must contain 8 digits "

    if not any (char.isupper() for char in password ):
        return "weak : password must contain at least 1 upper case"

    if not any (char.islower() for char in password ):
        return "weak : password must contain at least 1 lower case "


    if not re.search(r'[@#$%&*^?><:]' ,  password ):
        return "medium : password must contain special characters "

    return "strong : your password is secured"

def password_checker():
    print("password strength checker is ready ")

    while True:
        password = input("enter your password (or type 'exit' to quiet):")

        if password.lower() == 'exit':
            print("thank u for using this tool")
            break

        result = check_password_strength (password)
        print(result)

if __name__ == "__main__" :
    password_checker()